//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2021.05.18 at 11:21:28 AM YEKT
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://davydov.com/shop/products", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.davydov.shop.soap.products;
