spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: root
    password: root
  jpa:
    show-sql: true
  liquibase:
    change-log: classpath:db/master.xml

logging:
  level:
    root: info
    org:
      springframework:
        web: debug
        hibernate: error
        data: error
  file:
    path: logs
  pattern:
    file: '%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %-5level %logger{36}.%M - %msg%n'
    console: '%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n'
